# Generated by Django 4.0.3 on 2022-04-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='sector_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'tele'), (2, 'water_and_sewage'), (3, 'roads_authority'), (4, 'elpa')], null=True),
        ),
    ]
