# Generated by Django 4.0.3 on 2022-03-19 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ForeignKey(db_column='rolesId', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
        ),
    ]
