# Generated by Django 4.0.3 on 2022-03-31 12:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sector_address_alter_sector_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ProfileUrl',
        ),
        migrations.AddField(
            model_name='customuser',
            name='ProfileImage',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
