# Generated by Django 4.0.3 on 2022-04-07 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sector_sector_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectoradmin',
            name='sector',
        ),
        migrations.AddField(
            model_name='sector',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector_admin', to='accounts.sectoradmin'),
        ),
    ]
