# Generated by Django 4.0.3 on 2022-03-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_superadmin_options_superadmin_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
