# Generated by Django 4.0.3 on 2022-04-07 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_sectoradmin_sector_sector_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='sector',
        ),
        migrations.AddField(
            model_name='sectoradmin',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='accounts.sector'),
        ),
    ]
