# Generated by Django 4.0.3 on 2022-05-15 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9xxxxxxxxxx'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
