# Generated by Django 4.0.3 on 2022-04-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_sector_sector_sectoradmin_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='main_sector',
            field=models.BooleanField(default=False),
        ),
    ]
