# Generated by Django 4.0.4 on 2022-05-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_strike',
            field=models.IntegerField(default=0),
        ),
    ]
