# Generated by Django 4.0.3 on 2022-03-24 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9xxxxxxxxx'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
