# Generated by Django 4.0.3 on 2022-04-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sector_main_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='sector_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
