# Generated by Django 4.0.3 on 2022-03-20 05:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_id'),
        ('accounts', '0003_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('cityName', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('description', models.CharField(max_length=255, null=True)),
                ('postedAt', models.DateTimeField(auto_now=True, null=True)),
                ('resolvedAt', models.DateTimeField(auto_now=True, null=True)),
                ('noOfLikes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('spamStatus', models.BooleanField(default=False)),
                ('state', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.location')),
                ('sectorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sector')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
