# Generated by Django 4.0.3 on 2022-03-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
