# Generated by Django 4.0.4 on 2022-05-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='state',
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('RESOLVED', 'RESOLVED'), ('UNRESOLVED', 'UNRESOLVED'), ('REJECTED', 'REJECTED')], default='UNRESOLVED', max_length=100),
        ),
    ]
