# Generated by Django 4.0.3 on 2022-03-28 22:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
