# Generated by Django 4.0.3 on 2022-05-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='resolvedAt',
            new_name='updatedAt',
        ),
    ]
