# Generated by Django 4.0.3 on 2022-03-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_phoneotp'),
        ('reports', '0004_alter_report_nooflikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
    ]
