# Generated by Django 4.0.3 on 2022-05-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_resolvedat_report_updatedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='noOfLikes',
        ),
        migrations.AddField(
            model_name='report',
            name='noOfLikes',
            field=models.IntegerField(default=0),
        ),
    ]
