# Generated by Django 4.0.3 on 2022-05-25 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0005_remove_report_nooflikes_report_nooflikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='noOfLikes',
        ),
        migrations.AddField(
            model_name='report',
            name='noOfLikes',
            field=models.ManyToManyField(related_name='report_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
