# Generated by Django 4.0.3 on 2022-03-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_phone_number'),
        ('reports', '0006_rename_sectorid_report_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='noOfLikes',
        ),
        migrations.AddField(
            model_name='report',
            name='noOfLikes',
            field=models.ManyToManyField(related_name='report_posts', to='accounts.customuser'),
        ),
    ]
