# Generated by Django 4.0.3 on 2022-03-25 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0007_remove_report_nooflikes_report_nooflikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='noOfLikes',
            field=models.ManyToManyField(related_name='report_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
