# Generated by Django 4.0.3 on 2022-05-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='likeornot',
            field=models.BooleanField(default=False),
        ),
    ]
