# Generated by Django 4.0.3 on 2022-03-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('sectorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sector')),
            ],
        ),
    ]
