# Generated by Django 4.0.3 on 2022-03-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='sectorId',
            new_name='sector',
        ),
    ]
