# Generated by Django 4.0.3 on 2022-05-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='date',
            new_name='updatedAt',
        ),
        migrations.AddField(
            model_name='announcement',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
