# Generated by Django 4.0.3 on 2022-03-21 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_roles'),
        ('announcment', '0002_rename_sectorid_announcement_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='sectoradmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sectoradmin'),
        ),
    ]
