# Generated by Django 4.0.3 on 2022-03-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='logged',
            field=models.BooleanField(default=False, help_text='If otp verification got successful'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ProfileUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
