# Generated by Django 4.0.3 on 2022-03-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_userid'),
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
